name: firebase_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: any
  firebase_storage: any
  cloud_firestore:
  get_cli: ^1.8.1
  get: 4.6.5
  cached_network_image: ^3.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

